/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv functions/cloudflare-env.d.ts` (hash: 89a16c7f95b21f21751215a01a1cf11f)
interface __BaseEnv_CloudflareEnv {
  SEARCH_RATE_LIMIT_DB: D1Database;
  SEARCH_INDEX: VectorizeIndex;
  ACECORE_NET_URL: "https://acecore.net";
  PUBLIC_APP_URL:
    "https://acecore-schools.pages.dev" | "https://schools.acecore.net";
  ALLOWED_ORIGINS:
    | "https://acecore-schools.pages.dev,https://acecore.net"
    | "https://schools.acecore.net,https://acecore.net";
  SEARCH_ENABLED: "true";
  SEARCH_MIN_SCORE: "0.50";
  OPENAI_EMBEDDING_MODEL: "text-embedding-3-large";
  OPENAI_EMBEDDING_DIMENSIONS: "1536";
}
declare namespace Cloudflare {
  interface PreviewEnv {
    SEARCH_RATE_LIMIT_DB: D1Database;
    SEARCH_INDEX: VectorizeIndex;
    ACECORE_NET_URL: "https://acecore.net";
    PUBLIC_APP_URL: "https://acecore-schools.pages.dev";
    ALLOWED_ORIGINS: "https://acecore-schools.pages.dev,https://acecore.net";
    SEARCH_ENABLED: "true";
    SEARCH_MIN_SCORE: "0.50";
    OPENAI_EMBEDDING_MODEL: "text-embedding-3-large";
    OPENAI_EMBEDDING_DIMENSIONS: "1536";
  }
  interface ProductionEnv {
    SEARCH_RATE_LIMIT_DB: D1Database;
    SEARCH_INDEX: VectorizeIndex;
    ACECORE_NET_URL: "https://acecore.net";
    PUBLIC_APP_URL: "https://schools.acecore.net";
    ALLOWED_ORIGINS: "https://schools.acecore.net,https://acecore.net";
    SEARCH_ENABLED: "true";
    SEARCH_MIN_SCORE: "0.50";
    OPENAI_EMBEDDING_MODEL: "text-embedding-3-large";
    OPENAI_EMBEDDING_DIMENSIONS: "1536";
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
