/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv functions/cloudflare-env.d.ts` (hash: bfe3c11641dddee9e4093f2ff4b353d5)
interface __BaseEnv_CloudflareEnv {
  SEARCH_RATE_LIMIT_DB: D1Database;
  ACECORE_NET_URL: "https://acecore.net";
  PUBLIC_APP_URL:
    "https://acecore-schools.pages.dev" | "https://schools.acecore.net";
  ALLOWED_ORIGINS:
    | "https://acecore-schools.pages.dev,https://acecore.net"
    | "https://schools.acecore.net,https://acecore.net";
  SEARCH_ENABLED: "false" | "true";
  SEARCH_MIN_SCORE: "0.50";
  SEARCH_EMBEDDING_MODEL: "@cf/baai/bge-m3";
  SEARCH_EMBEDDING_DIMENSIONS: "1024";
  ACECORE_CHAT:
    | Fetcher /* acecore-chat-worker-preview */
    | Fetcher /* acecore-chat-worker */;
  SEARCH_INDEX?: VectorizeIndex;
  AI?: Ai;
}
declare namespace Cloudflare {
  interface PreviewEnv {
    SEARCH_RATE_LIMIT_DB: D1Database;
    ACECORE_NET_URL: "https://acecore.net";
    PUBLIC_APP_URL: "https://acecore-schools.pages.dev";
    ALLOWED_ORIGINS: "https://acecore-schools.pages.dev,https://acecore.net";
    SEARCH_ENABLED: "false";
    SEARCH_MIN_SCORE: "0.50";
    SEARCH_EMBEDDING_MODEL: "@cf/baai/bge-m3";
    SEARCH_EMBEDDING_DIMENSIONS: "1024";
    ACECORE_CHAT: Fetcher /* acecore-chat-worker-preview */;
  }
  interface ProductionEnv {
    SEARCH_RATE_LIMIT_DB: D1Database;
    SEARCH_INDEX: VectorizeIndex;
    AI: Ai;
    ACECORE_NET_URL: "https://acecore.net";
    PUBLIC_APP_URL: "https://schools.acecore.net";
    ALLOWED_ORIGINS: "https://schools.acecore.net,https://acecore.net";
    SEARCH_ENABLED: "true";
    SEARCH_MIN_SCORE: "0.50";
    SEARCH_EMBEDDING_MODEL: "@cf/baai/bge-m3";
    SEARCH_EMBEDDING_DIMENSIONS: "1024";
    ACECORE_CHAT: Fetcher /* acecore-chat-worker */;
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
