/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv functions/cloudflare-env.d.ts` (hash: ef2c918cd48b902f1200be4057b1f31f)
interface __BaseEnv_CloudflareEnv {
  SEARCH_RATE_LIMIT_DB: D1Database;
  SEARCH_INDEX: VectorizeIndex;
  AI: Ai;
  ACECORE_NET_URL: "https://acecore.net";
  PUBLIC_APP_URL:
    "https://acecore-schools.pages.dev" | "https://schools.acecore.net";
  ALLOWED_ORIGINS:
    | "https://acecore-schools.pages.dev,https://acecore.net"
    | "https://schools.acecore.net,https://acecore.net";
  SEARCH_ENABLED: "true" | "false";
  SEARCH_MIN_SCORE: "0.50";
}
declare namespace Cloudflare {
  interface PreviewEnv {
    SEARCH_RATE_LIMIT_DB: D1Database;
    SEARCH_INDEX: VectorizeIndex;
    AI: Ai;
    ACECORE_NET_URL: "https://acecore.net";
    PUBLIC_APP_URL: "https://acecore-schools.pages.dev";
    ALLOWED_ORIGINS: "https://acecore-schools.pages.dev,https://acecore.net";
    SEARCH_ENABLED: "true";
    SEARCH_MIN_SCORE: "0.50";
  }
  interface ProductionEnv {
    SEARCH_RATE_LIMIT_DB: D1Database;
    SEARCH_INDEX: VectorizeIndex;
    AI: Ai;
    ACECORE_NET_URL: "https://acecore.net";
    PUBLIC_APP_URL: "https://schools.acecore.net";
    ALLOWED_ORIGINS: "https://schools.acecore.net,https://acecore.net";
    SEARCH_ENABLED: "true";
    SEARCH_MIN_SCORE: "0.50";
  }
  interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
